# DevOpsGPT Configuration

# LLM Configuration
llm:
  # Default provider - can be "openai" or "ollama"
  provider: "ollama"
  
  # Ollama settings (primary)
  base_url: "http://localhost:11434"
  model: "llama2"
  max_tokens: 500

  # OpenAI settings (optional fallback)
  fallback_provider: false
  openai_api_key: "${OPENAI_API_KEY}"
  openai_model: "gpt-4"

# Security Settings
security:
  require_confirmation: true
  dry_run_by_default: true
  audit_logging: true
  allowed_operations:
    - "restart"
    - "scale"
    - "deploy"
    - "rollback"
  restricted_operations:
    - "delete"
    - "terminate"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/devops_gpt.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
